name: Update Algolia index with BGG data

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs every 12 hour
  workflow_dispatch:
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: python -m pip install --upgrade pip
    - run: pip install -r scripts/requirements.txt
    - name: Run script if secret is set
      env:
        APIKEY: ${{secrets.APIKEY}}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      if: env.APIKEY != null
      run: |
        python scripts/download_and_index.py --apikey ${{env.APIKEY}}
